#!/usr/bin/env bash

if (( EUID != 0 ))
then
    exec sudo "$0" "$@"
fi

set -euo pipefail
shopt -s nullglob

LC_ALL="C"
LANG="C"
LANGUAGE="C"

DEBUG="${DEBUG:-false}"

source "/usr/lib/vicharak-config/cli/main.sh"

VICHARAK_CONFIG_EXEC_NAME="$(basename "$0")"
if (( $# == 0 )) && [[ "$VICHARAK_CONFIG_EXEC_NAME" == "vicharak-config" ]]
then
    source "/usr/lib/vicharak-config/tui/main.sh"
    tui_start __tui_main
else
    if [[ "$VICHARAK_CONFIG_EXEC_NAME" == "vicharak-config" ]]
    then
        __parameter_type_check "$1" "function"
        "$@"
    else
        __parameter_type_check "__$VICHARAK_CONFIG_EXEC_NAME" "function"
        "__$VICHARAK_CONFIG_EXEC_NAME" "$@"
    fi
    
fi
